before_install:
  - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/estan:/protoc-gen-doc/xUbuntu_14.04/ /' > /etc/apt/sources.list.d/protoc-gen-doc.list"
  - wget -nv http://download.opensuse.org/repositories/home:estan:protoc-gen-doc/xUbuntu_14.04/Release.key -O Release.key
  - sudo apt-key add - < Release.key
  - sudo apt-get update
  - sudo apt-get install protobuf-compiler
  - sudo apt-get --allow-unauthenticated install protoc-gen-doc
  - mkdir build && mkdir build/html
  - cp docgen/stylesheet.css build/html
  - protoc --doc_out=html,index.html:build/html *.proto
language: node_js
node_js:
  - "6"
  - "4"
  - "0.12"
  - "0.10"
deploy:
  provider: pages
  skip_cleanup: true
  name: datproject
  local_dir: build/html
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
